### PR TITLE
GitHub CI: run on Emacs 29.2

### PR DESCRIPTION
**Pull request by basil-conto**

### CODE REVIEW

**Comment by mattiase** [comment]
Thanks!

**Comment by basil-conto** [comment]
Artisanal unautomated ping that this can be bumped to 29.3 now.

**Comment by mattiase** [comment]
> Artisanal unautomated ping that this can be bumped to 29.3 now.

Done, thank you!

**Comment by basil-conto** [comment]
> Artisanal unautomated ping that this can be bumped to 29.3 now.

Which can now be bumped to 29.4 and `actions/checkout@v4` to `actions/checkout@v5` both here and for `relint`.

**Comment by mattiase** [comment]
> Which can now be bumped to 29.4 and actions/checkout@v4 to actions/checkout@v5 both here and for relint.

Adjusted, thank you!

**Pull request merged**
